Repository hugo-toha/toha, pull requests merged in 2020-11, with the labels that each got.

#145 Add dependabot.yaml
  .github/dependabot.yml
Labels: enhancement

#147 Remove submodules section from dependabot.yml
  .github/dependabot.yml
Labels: bug-fix

#148 Update workflows to use latest release instead of master branch
  .github/workflows/autoprefixer.yml
  .github/workflows/draft-release.yml
Labels: enhancement

#151 Add new badges
  README.md
Labels: automerge, enhancement

#152 Added Spanish i18n
  i18n/es.toml
Labels: translation

#158 Update theme.toml
  theme.toml
Labels: automerge, enhancement

#161 Improve de.toml
  .gitignore
  i18n/de.toml
Labels: automerge, enhancement

#164 Fix smooth scroll
  static/assets/js/main.js
Labels: automerge, bug-fix

#166 Italian menu item, Italian translation for the i18n file, and Italian example site
  exampleSite/config.yaml
  exampleSite/data/it/author.yaml
  exampleSite/data/it/sections/about.yaml
  exampleSite/data/it/sections/achievements.yaml
  exampleSite/data/it/sections/experiences.yaml
  exampleSite/data/it/sections/projects.yaml
  exampleSite/data/it/sections/recent-posts.yaml
  exampleSite/data/it/sections/skills.yaml
  exampleSite/data/it/site.yaml
  i18n/it.toml
Labels: translation
