Repository hugo-toha/toha, pull requests merged in 2020-10, with the labels that each got.

#60 Translations and i18n
  exampleSite/config.yaml
  exampleSite/data/bn/author.yaml
  exampleSite/data/bn/sections/about.yaml
  exampleSite/data/bn/sections/achievements.yaml
  exampleSite/data/bn/sections/experiences.yaml
  exampleSite/data/bn/sections/projects.yaml
  exampleSite/data/bn/sections/recent-posts.yaml
  exampleSite/data/bn/sections/skills.yaml
  exampleSite/data/bn/site.yaml
  exampleSite/data/en/author.yaml
  exampleSite/data/en/sections/about.yaml
  exampleSite/data/en/sections/achievements.yaml
  exampleSite/data/en/sections/experiences.yaml
  exampleSite/data/en/sections/projects.yaml
  exampleSite/data/en/sections/recent-posts.yaml
  exampleSite/data/en/sections/skills.yaml
  exampleSite/data/en/site.yaml
  exampleSite/data/fr/author.yaml
  exampleSite/data/fr/sections/about.yaml
  exampleSite/data/fr/sections/achievements.yaml
  exampleSite/data/fr/sections/experiences.yaml
  exampleSite/data/fr/sections/projects.yaml
  exampleSite/data/fr/sections/recent-posts.yaml
  exampleSite/data/fr/sections/skills.yaml
  exampleSite/data/fr/site.yaml
  i18n/bn.toml
  i18n/en.toml
  i18n/fr.toml
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/cards/post.html
  layouts/partials/cards/project.html
  layouts/partials/cards/skill.html
  layouts/partials/footer.html
  layouts/partials/header.html
  layouts/partials/helpers/country-code.html
  layouts/partials/navigators/floating-lang-selector.html
  layouts/partials/navigators/lang-selector-2.html
  layouts/partials/navigators/lang-selector.html
  layouts/partials/navigators/navbar-2.html
  layouts/partials/navigators/navbar.html
  layouts/partials/navigators/sidebar.html
  layouts/partials/scripts.html
  layouts/partials/sections/about.html
  layouts/partials/sections/achievements/entry.html
  layouts/partials/sections/home.html
  package-lock.json
  package.json
  static/assets/css/layouts/list.css
  static/assets/css/layouts/main.css
  static/assets/css/layouts/single.css
  static/assets/css/navigators/navbar.css
  static/assets/css/sections/home.css
  static/assets/js/main.js
  static/assets/js/popper.min.js
Labels: breaking-change, feature

#91 Fix post url
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/partials/navigators/navbar.html
Labels: bug

#95 Fix URL in footer
  layouts/partials/footer.html
Labels: bug-fix

#114 Fix about section to pull author name correctly
  layouts/partials/sections/about.html
Labels: bug-fix

#115 add ios specific css for fixing the background images
  static/assets/css/sections/home.css
Labels: bug-fix

#112 Add nav item data and aria attributes to collapse the nav bar in mobile
  layouts/partials/navigators/navbar.html
Labels: bug-fix

#110 Update readme with contributing guide and create github templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation, enhancement

#120 fix URLs when serving from a subdirectory (fixes #89)
  layouts/404.html
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/footer.html
  layouts/partials/header.html
  layouts/partials/scripts.html
Labels: bug-fix

#118 Add Indonesian Language for Toha Themes
  .gitignore
  exampleSite/config.yaml
  exampleSite/data/id/author.yaml
  exampleSite/data/id/sections/about.yaml
  exampleSite/data/id/sections/achievements.yaml
  exampleSite/data/id/sections/experiences.yaml
  exampleSite/data/id/sections/projects.yaml
  exampleSite/data/id/sections/recent-posts.yaml
  exampleSite/data/id/sections/skills.yaml
  exampleSite/data/id/site.yaml
  i18n/id.toml
Labels: language-support

#107 Fix the single template to use the authors avatar correctly
  README.md
  exampleSite/config.yaml
  layouts/404.html
  layouts/_default/baseof.html
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/cards/project.html
  layouts/partials/cards/skill.html
  layouts/partials/disqus.html
  layouts/partials/footer.html
  layouts/partials/header.html
  layouts/partials/helpers/get-author-image.html
  layouts/partials/helpers/get-author-name.html
  layouts/partials/navigators/floating-lang-selector.html
  layouts/partials/navigators/lang-selector-2.html
  layouts/partials/navigators/lang-selector.html
  layouts/partials/navigators/navbar-2.html
  layouts/partials/navigators/navbar.html
  layouts/partials/sections/about.html
  layouts/partials/sections/achievements/entry.html
  layouts/partials/sections/home.html
Labels: bug-fix, hacktoberfest-accepted

#133 Add 'New Translations` section in release notes
  .github/release-drafter.yml
Labels: enhancement

#125 Fixed post link error on sidebar
  layouts/_default/list.html
Labels: bug-fix

#135 Add kodiak integration for automatically merge PR
  .github/workflows/autoprefixer.yml
  .kodiak.toml
Labels: automerge

#136 Add status badge
  README.md
Labels: automerge

#141 Fix the get author name partial to account for localized author names
  layouts/partials/helpers/get-author-name.html
Labels: bug-fix

#138 Fix the nav item collapse and spy functionality
  layouts/partials/navigators/navbar.html
  static/assets/js/navbar.js
Labels: hacktoberfest-accepted

#142 Fix translation + navbar CSS
  i18n/bn.toml
  i18n/de.toml
  i18n/en.toml
  i18n/fr.toml
  i18n/id.toml
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/partials/navigators/next-prev-navigator.html
  static/assets/css/layouts/single.css
Labels: automerge, bug-fix
