Repository hugo-toha/toha, pull requests merged in 2020-12, with the labels that each got.

#177 Add ja.toml
  i18n/ja.toml
Labels: translation

#178 Add label enforcer workflow
  .github/workflows/enforce-label.yml
Labels: enhancement

#181 Fix: Fail to import a country flag of Japan.
  i18n/jp.toml
Labels: automerge, bug-fix

#194 es -> it for italian language code
  exampleSite/config.yaml
Labels: automerge, bug-fix

#199 Added toml file for Vietnamese translation
  i18n/vn.toml
Labels: automerge, translation

#198 translate_Chinese
  exampleSite/config.yaml
  exampleSite/data/cn/author.yaml
  exampleSite/data/cn/sections/about.yaml
  exampleSite/data/cn/sections/achievements.yaml
  exampleSite/data/cn/sections/experiences.yaml
  exampleSite/data/cn/sections/projects.yaml
  exampleSite/data/cn/sections/recent-posts.yaml
  exampleSite/data/cn/sections/skills.yaml
  exampleSite/data/cn/site.yaml
  i18n/cn.toml
Labels: automerge, translation

#197 explicitly set the default language (needed for English not being the…
  exampleSite/config.yaml
Labels: automerge, enhancement

#187 Change the behavior of card links
  layouts/partials/cards/project.html
  layouts/partials/cards/skill.html
Labels: automerge, bug-fix

#173 Transition to Hugo Image Processing
  .gitignore
  archetypes/default.md
  assets/images/404.png
  assets/images/404.svg
  assets/images/default-avatar.png
  assets/images/default-background.jpg
  assets/images/default-hero.jpg
  assets/images/favicon.png
  assets/images/hugo-logo.svg
  assets/images/inverted-logo.png
  assets/images/main-logo.png
  assets/images/theme-logo.png
  exampleSite/assets/images/author/jessica.png
  exampleSite/assets/images/author/john.png
  exampleSite/assets/images/sections/achievements/graduation-cap.jpg
  exampleSite/assets/images/sections/achievements/presenter.jpg
  exampleSite/assets/images/sections/achievements/sport.jpg
  exampleSite/assets/images/sections/achievements/woman-winner.jpg
  exampleSite/assets/images/sections/projects/kubernetes.png
  exampleSite/assets/images/sections/projects/no-code.png
  exampleSite/assets/images/sections/projects/tensorflow.png
  exampleSite/assets/images/sections/projects/toha.png
  exampleSite/assets/images/sections/skills/c++.png
  exampleSite/assets/images/sections/skills/cloud.png
  exampleSite/assets/images/sections/skills/docker.svg
  exampleSite/assets/images/sections/skills/git.png
  exampleSite/assets/images/sections/skills/go.png
  exampleSite/assets/images/sections/skills/kubernetes.png
  exampleSite/assets/images/sections/skills/linux.png
  exampleSite/assets/images/sections/skills/prometheus.png
  exampleSite/assets/images/site/background.jpg
  exampleSite/assets/images/site/favicon.png
  exampleSite/assets/images/site/inverted-logo.png
  exampleSite/assets/images/site/main-logo.png
  exampleSite/data/bn/sections/skills.yaml
  exampleSite/data/en/sections/skills.yaml
  exampleSite/data/fr/sections/skills.yaml
  exampleSite/data/id/sections/skills.yaml
  exampleSite/data/it/sections/skills.yaml
  layouts/404.html
  layouts/_default/single.html
  layouts/partials/cards/project.html
  layouts/partials/cards/skill.html
  layouts/partials/footer.html
  layouts/partials/header.html
  layouts/partials/helpers/get-author-image.html
  layouts/partials/helpers/get-hero.html
  layouts/partials/navigators/navbar-2.html
  layouts/partials/navigators/navbar.html
  layouts/partials/sections/achievements/entry.html
  layouts/partials/sections/home.html
  layouts/shortcodes/rimg.html
  static/assets/js/home.js
Labels: automerge, breaking-change, enhancement
