Repository hugo-toha/toha, pull requests merged in 2021-03, with the labels that each got.

#246 Add a `tel:` link to the About Page
  layouts/partials/sections/about.html
Labels: automerge, feature

#248 Fix to the hero so you can have the image named anything you want
  layouts/partials/helpers/get-hero.html
Labels: automerge, bug-fix

#243 Display project card technology tags
  exampleSite/data/bn/sections/projects.yaml
  exampleSite/data/cn/sections/projects.yaml
  exampleSite/data/en/sections/projects.yaml
  exampleSite/data/id/sections/projects.yaml
  layouts/partials/cards/project.html
  static/css/sections/projects.css
Labels: feature

#234 Add more i18n strings
  i18n/bn.toml
  i18n/cn.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/id.toml
  i18n/it.toml
  i18n/jp.toml
  i18n/ko.toml
  i18n/ru.toml
  i18n/vn.toml
  layouts/404.html
  layouts/partials/cards/post.html
  layouts/partials/cards/project.html
  layouts/partials/cards/recent-post.html
  layouts/partials/disqus.html
  layouts/partials/sections/experiences/multiple-positions.html
Labels: enhancement, translation

#213 Add back to top
  layouts/_default/single.html
  static/css/layouts/single.css
  static/js/single.js
Labels: feature

#254 Fix minor typos in README file
  README.md
Labels: automerge, documentation, enhancement

#256 Fix missing vertical separator in navbar menu
  layouts/partials/navigators/navbar.html
Labels: bug-fix

#257 Fix courses visibility toggler button
  i18n/bn.toml
  i18n/cn.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/id.toml
  i18n/it.toml
  i18n/jp.toml
  i18n/ko.toml
  i18n/ru.toml
  i18n/vn.toml
  layouts/partials/sections/education-alt.html
  layouts/partials/sections/education.html
  static/js/main.js
Labels: automerge, bug-fix

#258 Fix next-prev navigator for large title
  layouts/partials/navigators/next-prev-navigator.html
  static/css/layouts/single.css
Labels: automerge, bug-fix

#261 Footer navigation links fix
  layouts/partials/footer.html
Labels: bug-fix

#268 Fix actions branch ref + move some CSS from `single.css` into `main.css`
  .github/workflows/autoprefixer.yml
  .github/workflows/draft-release.yml
  static/css/layouts/main.css
  static/css/layouts/single.css
Labels: automerge, bug-fix

#269 Fix table CSS in Education section
  static/css/sections/education.css
Labels: automerge, bug-fix

#270 Fix various issues detected by html-proofer
  layouts/404.html
  layouts/_default/search.html
  layouts/_default/single.html
  layouts/partials/cards/post.html
  layouts/partials/footer.html
  layouts/partials/navigators/floating-lang-selector.html
  layouts/partials/navigators/lang-selector-2.html
  layouts/partials/navigators/lang-selector.html
  layouts/partials/navigators/navbar-2.html
  layouts/partials/navigators/navbar.html
  layouts/partials/sections/home.html
Labels: bug-fix
