Repository hugo-toha/toha, pull requests merged in 2021-01, with the labels that each got.

#203 Make list.html fully generic
  layouts/_default/list.html
Labels: automerge, enhancement

#168 Add education section
  exampleSite/data/bn/sections/education.yaml
  exampleSite/data/en/sections/education.yaml
  i18n/bn.toml
  i18n/cn.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/id.toml
  i18n/it.toml
  i18n/jp.toml
  i18n/ru.toml
  i18n/vn.toml
  layouts/index.html
  layouts/partials/sections/education-alt.html
  layouts/partials/sections/education.html
  static/assets/css/layouts/main.css
  static/assets/css/sections/education.css
  static/assets/js/main.js
Labels: feature

#207 Remove images from static folders
  exampleSite/static/images/author/jessica.png
  exampleSite/static/images/author/john.png
  exampleSite/static/images/sections/achievements/presenter.jpg
  exampleSite/static/images/sections/achievements/sport.jpg
  exampleSite/static/images/sections/achievements/woman-winner.jpg
  exampleSite/static/images/sections/projects/kubernetes.png
  exampleSite/static/images/sections/projects/no-code.png
  exampleSite/static/images/sections/projects/toha.png
  exampleSite/static/images/sections/skills/c++.png
  exampleSite/static/images/sections/skills/git.png
  exampleSite/static/images/sections/skills/go.png
  exampleSite/static/images/sections/skills/kubernetes.png
  exampleSite/static/images/sections/skills/prometheus.png
  exampleSite/static/images/site/favicon.png
  exampleSite/static/images/site/inverted-logo.png
  exampleSite/static/images/site/main-logo.png
  static/assets/images/404.png
  static/assets/images/404.svg
  static/assets/images/default-avatar.png
  static/assets/images/default-background.jpg
  static/assets/images/default-hero.jpg
  static/assets/images/favicon.png
  static/assets/images/hugo-logo-wide.svg
  static/assets/images/inverted-logo.png
  static/assets/images/main-logo.png
Labels: automerge, enhancement

#208 Remove "assets" prefix from "static" folder
  layouts/404.html
  layouts/_default/list.html
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/header.html
  layouts/partials/scripts.html
  package.json
  static/css/404.css
  static/css/bootstrap.min.css
  static/css/layouts/list.css
  static/css/layouts/main.css
  static/css/layouts/single.css
  static/css/navigators/navbar.css
  static/css/navigators/sidebar.css
  static/css/sections/about.css
  static/css/sections/achievements.css
  static/css/sections/education.css
  static/css/sections/experiences.css
  static/css/sections/home.css
  static/css/sections/projects.css
  static/css/sections/recent-posts.css
  static/css/sections/skills.css
  static/css/style.css
  static/js/bootstrap.min.js
  static/js/github-button.js
  static/js/home.js
  static/js/itype.min.js
  static/js/jquery-3.4.1.min.js
  static/js/jquery.filterizr.min.js
  static/js/list.js
  static/js/main.js
  static/js/navbar.js
  static/js/popper.min.js
  static/js/single.js
Labels: automerge, breaking-change, enhancement

#210 Translate chinese
  README.md
  exampleSite/data/cn/sections/achievements.yaml
  exampleSite/data/cn/sections/education.yaml
  exampleSite/data/cn/sections/projects.yaml
  exampleSite/data/cn/sections/recent-posts.yaml
  exampleSite/data/cn/site.yaml
  exampleSite/data/en/sections/achievements.yaml
  exampleSite/data/en/sections/projects.yaml
  exampleSite/data/en/sections/recent-posts.yaml
  i18n/cn.toml
Labels: automerge, translation

#215 Fix missing space in cn/sections.projects.yaml
  exampleSite/data/cn/sections/projects.yaml
Labels: automerge, bug-fix

#216 add hindi translation
  i18n/hi.toml
  layouts/partials/helpers/country-code.html
Labels: automerge, translation

#218 Fix main logos default path
  layouts/partials/navigators/navbar.html
Labels: automerge, bug-fix

#217 [i18n] We also write navigation without 'u' in french
  i18n/fr.toml
Labels: automerge, enhancement

#219 Markdownify copyright notice
  layouts/partials/footer.html
Labels: automerge, enhancement

#222 parameterize git branch
  README.md
  exampleSite/config.yaml
  layouts/_default/single.html
Labels: automerge, enhancement

#220 Add Korean i18n
  i18n/ko.toml
Labels: automerge, translation
