Repository hugo-toha/toha, pull requests merged in 2021-11, with the labels that each got.

#454 Update Issue Automation
  .github/workflows/project-automation-issue.yaml
  .github/workflows/project-automation-pr.yaml
Labels: enhancement, hacktoberfest

#456 Find Linked Issues to a PR
  .github/workflows/issue_parser.yaml
  .github/workflows/project-automation-pr.yaml
Labels: enhancement, automerge

#465 Add utteranc comment plugin
  layouts/_default/single.html
  layouts/partials/utteranc.html
Labels: feature
