Repository hugo-toha/toha, pull requests merged in 2021-08, with the labels that each got.

#393 education-line
  static/css/sections/education.css
Labels: bug-fix, automerge

#394 Allow setting GIFS as author image
  layouts/partials/helpers/get-author-image.html
  layouts/partials/sections/home.html
Labels: bug-fix, automerge

#395 Configure the number of posts in recent posts
  layouts/partials/sections/recent-posts.html
Labels: enhancement, automerge

#397 Fix multiple active menu in taxonomy
  layouts/partials/navigators/taxonomies.html
Labels: bug-fix, automerge

#402 Add Blogtrottr as newsletter provider
  layouts/partials/footer.html
Labels: feature

#409 Update es.toml
  i18n/es.toml
Labels: translation, automerge
