Repository hugo-toha/toha, pull requests merged in 2021-06, with the labels that each got.

#338 Fix importing user CSS
  layouts/_default/list.html
  layouts/_default/search.html
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/header.html
Labels: automerge, bug, bug-fix

#335 Fix typo in comment
  layouts/partials/header.html
Labels: automerge, enhancement

#341 Fix `ressource.Fit` not resizing the image properly
  layouts/partials/cards/project.html
  layouts/partials/cards/skill.html
  layouts/partials/helpers/get-author-image.html
  layouts/partials/sections/home.html
Labels: automerge, bug-fix

#343 Fix some french translations
  i18n/fr.toml
Labels: automerge, translation

#336 Disable logo by default + add logo only if the user provide it
  layouts/partials/header.html
  layouts/partials/navigators/navbar-2.html
  layouts/partials/navigators/navbar.html
  static/js/navbar.js
Labels: bug-fix

#342 Skillcards height css instead js
  static/css/sections/skills.css
  static/js/home.js
Labels: automerge, enhancement

#347 Fix horizontal scrollbar
  static/css/layouts/main.css
  static/css/sections/about.css
  static/css/sections/skills.css
Labels: automerge, bug-fix

#348 Fix Prev/Next navigator was not pointing to the actual prev/next article
  layouts/partials/helpers/get-pages.html
  layouts/partials/navigators/next-prev-navigator.html
Labels: automerge, bug-fix

#350 Add greeting subtitle
  layouts/partials/sections/home.html
  static/css/sections/home.css
Labels: feature

#353 Support Google Analytics v4
  layouts/_default/baseof.html
  layouts/index.html
Labels: automerge, enhancement

#359 358 error next prev page
  layouts/partials/navigators/next-prev-navigator.html
Labels: bug-fix

#357 Make newsletter helper label clear to complaint with GDPR
  i18n/bn.toml
  i18n/cn.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/id.toml
  i18n/it.toml
  i18n/jp.toml
  i18n/ko.toml
  i18n/nl.toml
  i18n/ru.toml
  i18n/vn.toml
Labels: automerge, enhancement

#363 Fix Google Analytic not showing up for v3 ID
  layouts/_default/baseof.html
  layouts/index.html
  layouts/partials/navigators/next-prev-navigator.html
Labels: automerge, bug-fix
