Repository hugo-toha/toha, pull requests merged in 2021-09, with the labels that each got.

#413 Corrected the word "Details" and another minor capitalization change.
  i18n/fr.toml
Labels: translation, automerge

#403 Added new 'GitForge' param for non GitHub repos
  layouts/_default/single.html
Labels: enhancement, enhancements, automerge

#417 Add some french translations
  i18n/fr.toml
Labels: translation, automerge

#418 Fix `View certificate` Italian translation
  i18n/it.toml
Labels: translation, automerge

#415 Added some social buttons to the "Post" template
  i18n/bn.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/id.toml
  i18n/it.toml
  i18n/jp.toml
  i18n/ko.toml
  i18n/nl.toml
  i18n/ru.toml
  i18n/vn.toml
  i18n/zh-cn.toml
  i18n/zh-tw.toml
  layouts/_default/single.html
  static/css/layouts/main.css
  static/css/layouts/single.css
Labels: feature

#421 Update dependency for security issue
  layouts/partials/misc/badge.html
  package-lock.json
Labels: enhancement, automerge

#422 Update plyrjs
  static/css/plyr.css
  static/js/plyr.js
Labels: enhancement, automerge

#427 Update Simplified Chinese and Traditional Chinese.
  i18n/zh-cn.toml
  i18n/zh-tw.toml
Labels: translation, automerge
