Repository hugo-toha/toha, pull requests merged in 2021-05, with the labels that each got.

#303 Allow footer configuration
  layouts/_default/baseof.html
  layouts/index.html
  layouts/partials/footer.html
Labels: enhancement

#274 Fix note layout
  layouts/notes/list.html
  layouts/notes/single.html
  layouts/partials/helpers/add-navbar-separator.html
  layouts/partials/navigators/navbar.html
  layouts/partials/note-aggregator.html
  layouts/shortcodes/note.html
  static/css/layouts/notes.css
  static/js/imagesloaded.pkgd.min.js
  static/js/note.js
Labels: breaking-change, feature

#313 Update postcss-cli and autoprefixer
  package-lock.json
  package.json
Labels: automerge, enhancement

#314 Add CodeQL Security analysis
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#312 Add a disclaimer in the footer of each page.
  i18n/bn.toml
  i18n/cn.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/id.toml
  i18n/it.toml
  i18n/jp.toml
  i18n/ko.toml
  i18n/ru.toml
  i18n/vn.toml
  layouts/partials/footer.html
  static/css/layouts/main.css
  static/css/layouts/single.css
  static/css/navigators/sidebar.css
Labels: enhancement

#311 In case the old config already deactivated the newletter, it must be …
  layouts/partials/footer.html
Labels: automerge, bug-fix

#308 Mailchimp
  layouts/partials/footer.html
Labels: automerge, enhancement

#307 Support adding verifiable `Certifications` badge in about section
  layouts/partials/misc/badge.html
  layouts/partials/misc/soft-skills.html
  layouts/partials/sections/about.html
Labels: automerge, breaking-change, enhancement

#316 Allow overwriting country flag for a language
  layouts/partials/helpers/country-code.html
  static/css/layouts/main.css
Labels: automerge, enhancement

#305 Make search multilingual
  content/notes/search.bn.md
  content/notes/search.cn.md
  content/notes/search.de.md
  content/notes/search.es.md
  content/notes/search.fr.md
  content/notes/search.hi.md
  content/notes/search.id.md
  content/notes/search.it.md
  content/notes/search.jp.md
  content/notes/search.ko.md
  content/notes/search.ru.md
  content/notes/search.vn.md
  content/posts/search.bn.md
  content/posts/search.cn.md
  content/posts/search.de.md
  content/posts/search.es.md
  content/posts/search.fr.md
  content/posts/search.hi.md
  content/posts/search.id.md
  content/posts/search.it.md
  content/posts/search.jp.md
  content/posts/search.ko.md
  content/posts/search.ru.md
  content/posts/search.vn.md
  layouts/_default/list.html
  layouts/_default/search.html
  layouts/_default/single.html
  layouts/notes/list.html
  layouts/notes/single.html
  layouts/partials/helpers/country-code.html
  layouts/partials/navigators/floating-lang-selector.html
  layouts/partials/navigators/lang-selector-2.html
  layouts/partials/navigators/lang-selector.html
  static/js/search.js
Labels: enhancement, translation

#320 Documentation mailchimp
  README.md
Labels: automerge, documentation, enhancement

#321 Fix auto-prefixer workflow
  .github/workflows/autoprefixer.yml
Labels: bug-fix

#326 Fix German translation + add Dutch translations
  i18n/de.toml
  i18n/nl.toml
Labels: automerge, translation

#333 Add OpenGraph Headers
  layouts/_default/baseof.html
  layouts/index.html
  layouts/partials/opengraph.html
Labels: automerge, feature
