Repository hugo-toha/toha, pull requests merged in 2021-04, with the labels that each got.

#279 fix navbar dropdown
  layouts/partials/navigators/navbar.html
Labels: bug-fix

#278 set url target link to blank
  layouts/partials/cards/accomplishments.html
  layouts/partials/cards/project.html
  layouts/partials/cards/skill.html
  layouts/partials/sections/about.html
  layouts/partials/sections/education.html
  layouts/partials/sections/experiences/multiple-positions.html
  layouts/partials/sections/experiences/single-position.html
Labels: enhancement

#282 Disable Auto-prefixer action
  .github/workflows/autoprefixer.yml
Labels: automerge, dependencies, enhancement

#285 Fix navbar togoller not showing in mobile and tablet
  static/css/layouts/main.css
Labels: automerge, bug-fix

#287 Fixed Errors in the Console issue #239
  static/css/bootstrap.min.css
  static/js/bootstrap.min.js
  static/js/itype.min.js
  static/js/popper.min.js
Labels: automerge, bug-fix

#288 Fix inconsistencies in target attributes
  layouts/partials/sections/about.html
Labels: enhancement

#290 Fix redirections to empty tabs
  layouts/partials/cards/accomplishments.html
  layouts/partials/cards/project.html
  layouts/partials/cards/skill.html
  layouts/partials/sections/education-alt.html
  layouts/partials/sections/education.html
Labels: automerge, bug-fix

#292 Refactor target values of redirections to external pages
  layouts/_default/single.html
  layouts/partials/footer.html
Labels: enhancement

#289 add video shortcode
  layouts/partials/header.html
  layouts/partials/scripts.html
  layouts/shortcodes/video.html
  static/css/plyr.css
  static/js/main.js
  static/js/plyr.js
Labels: enhancement

#296 Accessibility and SEO improvements
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/cards/accomplishments.html
  layouts/partials/cards/project.html
  layouts/partials/cards/recent-post.html
  layouts/partials/cards/skill.html
  layouts/partials/footer.html
  layouts/partials/navigators/navbar.html
  layouts/partials/navigators/next-prev-navigator.html
  layouts/partials/navigators/sidebar.html
  layouts/partials/note-aggregator.html
  layouts/partials/sections/about.html
  layouts/partials/sections/education-alt.html
  layouts/partials/sections/education.html
  layouts/partials/sections/experiences/multiple-positions.html
  layouts/partials/sections/experiences/single-position.html
  layouts/partials/sections/home.html
Labels: enhancement

#300 Use verbose flags in Readme
  README.md
Labels: automerge, enhancement

#302 Readme: Give each badge it's own line
  README.md
Labels: automerge, enhancement
