Repository hugo-toha/toha, pull requests merged in 2021-07, with the labels that each got.

#369 Remove about section whitespace when there are no soft skills/badges
  layouts/partials/sections/about.html
Labels: automerge, enhancement

#372 Add zh.toml
  i18n/zh.toml
Labels: automerge, translation

#376 Added svg support for project icons
  layouts/partials/cards/project.html
Labels: automerge, bug-fix

#383 Translate chinese
  i18n/zh-cn.toml
  i18n/zh-tw.toml
Labels: translation

#385 Add text link support for disclaimer.
  i18n/zh-cn.toml
  layouts/partials/footer.html
Labels: automerge, enhancement
