Repository hugo-toha/toha, pull requests merged in 2022-10, with the labels that each got.

#651 Update repo-URLs
  .github/ISSUE_TEMPLATE/feature_request.md
  layouts/partials/footer.html
  package.json
  static/css/sections/home.css
Labels: enhancement, automerge, hacktoberfest

#660 Portuguese translation
  README.md
  i18n/pt.toml
Labels: translation, automerge, hacktoberfest

#662 Improved german localization
  i18n/de.toml
Labels: translation, automerge

#650 Added Hugo-Module
  .gitignore
  go.mod
Labels: feature, automerge, hacktoberfest

#666 Only load flag CSS if showing flag icons
  layouts/partials/header.html
Labels: enhancement, automerge

#670 Allow custom hero images Fixes #379
  layouts/partials/helpers/get-hero.html
Labels: bug, automerge

#674 Fix counter.dev analytics
  layouts/partials/analytics.html
Labels: bug, automerge

#676 Better Support if browser blocks GoatCounter
  layouts/partials/analytics.html
  static/js/goat-counter.js
Labels: enhancement, automerge, hacktoberfest

#681 Centered Tags on Posts page
  layouts/_default/single.html
Labels: bug, automerge

#680 More Posts button
  layouts/partials/sections/recent-posts.html
Labels: enhancement, automerge
