Repository hugo-toha/toha, pull requests merged in 2022-01, with the labels that each got.

#486 Fix Nav-Bar when link to section of page
  static/js/navbar.js
Labels: bug, automerge

#488 Remove unused `adjustSkillCardsHeight();` function
  static/js/home.js
Labels: bug, automerge

#493 configurable navbar item count
  layouts/partials/navigators/navbar.html
Labels: enhancement, automerge

#499 Update footer.html
  layouts/partials/footer.html
Labels: bug, automerge

#502 Update experience-info.html
  layouts/partials/sections/experiences/experience-info.html
Labels: bug, automerge

#505 fix: navigation with hidden title
  layouts/partials/sections/accomplishments.html
  layouts/partials/sections/achievements.html
  layouts/partials/sections/education-alt.html
  layouts/partials/sections/education.html
  layouts/partials/sections/experiences.html
  layouts/partials/sections/projects.html
  layouts/partials/sections/recent-posts.html
  layouts/partials/sections/skills.html
Labels: bug, automerge

#509 Fix navbar missing an item in the dropdown
  layouts/partials/navigators/navbar.html
Labels: bug, automerge

#510 Tweaked background of table in education.css
  static/css/sections/education.css
Labels: bug, automerge

#512 Update skill.html
  layouts/partials/cards/skill.html
Labels: enhancement, automerge

#513 feat: customMenus in footer
  layouts/partials/footer.html
Labels: feature, automerge

#514 feat: configurable custom navbar items
  layouts/partials/navigators/navbar.html
Labels: enhancement, automerge

#516 add calculation to line up lines
  static/css/sections/experiences.css
Labels: bug, automerge

#517 feat: id for footer
  layouts/partials/footer.html
Labels: enhancement, automerge

#518 fix: correct tel: URL for translated about section
  layouts/partials/sections/about.html
Labels: bug, automerge
