Repository hugo-toha/toha, pull requests merged in 2022-11, with the labels that each got.

#684 Look for hero image in page bundle
  layouts/partials/helpers/get-hero.html
Labels: bug, automerge

#687 Fix recent-posts.html to not display search card
  layouts/partials/sections/recent-posts.html
Labels: bug, automerge

#690 Don't show search cards in search result
  layouts/_default/index.json
Labels: bug, automerge

#689 Add missing "alt" attributes to img tags in theme-selector.html
  layouts/partials/navigators/theme-selector.html
Labels: enhancement, automerge

#692 fix valine comment bug
  layouts/partials/comments/valine.html
Labels: bug, automerge

#696 Support external link in sidebar
  layouts/partials/navigators/sidebar.html
Labels: feature, automerge, hacktoberfest

#699 Fix typo in i18n/fr.toml
  i18n/fr.toml
Labels: translation, automerge

#703 Fix links of `posts`, `notes`, and `tags/%s` directories
  layouts/_default/single.html
  layouts/partials/navigators/navbar.html
Labels: enhancement, automerge
