Repository hugo-toha/toha, pull requests merged in 2022-02, with the labels that each got.

#528 [enhancement] Fix year in copyright notice
  layouts/partials/footer.html
Labels: enhancement, automerge

#521 fix: translated "Search" in search box
  i18n/bn.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fr.toml
  i18n/hi.toml
  i18n/id.toml
  i18n/it.toml
  i18n/jp.toml
  i18n/ko.toml
  i18n/nl.toml
  i18n/ru.toml
  i18n/vn.toml
  i18n/zh-cn.toml
  i18n/zh-tw.toml
  layouts/_default/list.html
  layouts/_default/search.html
  layouts/_default/single.html
  layouts/categories/list.html
  layouts/notes/list.html
  layouts/notes/single.html
  layouts/tags/list.html
Labels: translation, automerge

#540 Don't show `Responsibilities` header, if there aren't any
  layouts/partials/sections/experiences/single-position.html
Labels: bug, automerge

#542 add rss feed
  layouts/_default/rss.xml
Labels: feature, automerge

#543 Support commenting using `giscus`
  layouts/_default/single.html
  layouts/partials/giscus.html
Labels: feature, automerge
