Repository hugo-toha/toha, pull requests merged in 2022-03, with the labels that each got.

#545 Refine rss build logic
  layouts/_default/rss.xml
Labels: bug, automerge

#548 Auto build
  .github/workflows/build.yml
Labels: enhancement, automerge

#551 Add optional mermaid shortcode
  layouts/_default/single.html
  layouts/partials/mermaid.html
  layouts/shortcodes/mermaid.html
  static/js/mermaid-8.14.0.min.js
Labels: feature, automerge

#560 Use repoID and categoryID in giscus template
  README.md
  layouts/partials/giscus.html
Labels: bug, automerge

#565 Add finnish translation
  README.md
  i18n/fi.toml
Labels: translation, automerge

#570 fixed gitlab link
  layouts/_default/single.html
Labels: automerge

#564 Add commento.io support
  layouts/_default/single.html
  layouts/partials/comments.html
  layouts/partials/comments/commento.html
  layouts/partials/comments/disqus.html
  layouts/partials/comments/giscus.html
  layouts/partials/comments/utteranc.html
  layouts/partials/comments/valine.html
  layouts/partials/disqus.html
  layouts/partials/giscus.html
  layouts/partials/valine.html
Labels: feature, automerge
