Repository hugo-toha/toha, pull requests merged in 2022-09, with the labels that each got.

#638 Add Arabic language localization
  README.md
  i18n/ar.toml
Labels: translation, automerge

#640 Added functionality for use of any fontawesome icon and custom socials
  layouts/partials/footer.html
Labels: enhancement, automerge

#639 Local google font
  layouts/partials/header.html
  static/google-fonts/Mulish/Mulish-Italic-VariableFont_wght.ttf
  static/google-fonts/Mulish/Mulish-VariableFont_wght.ttf
  static/google-fonts/Mulish/OFL.txt
  static/google-fonts/Mulish/README.txt
  static/google-fonts/Mulish/mulish.css
  static/google-fonts/Mulish/static/Mulish-Black.ttf
  static/google-fonts/Mulish/static/Mulish-BlackItalic.ttf
  static/google-fonts/Mulish/static/Mulish-Bold.ttf
  static/google-fonts/Mulish/static/Mulish-BoldItalic.ttf
  static/google-fonts/Mulish/static/Mulish-ExtraBold.ttf
  static/google-fonts/Mulish/static/Mulish-ExtraBoldItalic.ttf
  static/google-fonts/Mulish/static/Mulish-ExtraLight.ttf
  static/google-fonts/Mulish/static/Mulish-ExtraLightItalic.ttf
  static/google-fonts/Mulish/static/Mulish-Italic.ttf
  static/google-fonts/Mulish/static/Mulish-Light.ttf
  static/google-fonts/Mulish/static/Mulish-LightItalic.ttf
  static/google-fonts/Mulish/static/Mulish-Medium.ttf
  static/google-fonts/Mulish/static/Mulish-MediumItalic.ttf
  static/google-fonts/Mulish/static/Mulish-Regular.ttf
  static/google-fonts/Mulish/static/Mulish-SemiBold.ttf
  static/google-fonts/Mulish/static/Mulish-SemiBoldItalic.ttf
Labels: enhancement, automerge

#642 Improve dutch translations
  i18n/nl.toml
Labels: translation, automerge

#644 Fix soft skill text wrapping issue
  static/css/sections/about.css
Labels: bug, automerge
