Repository hugo-toha/toha, pull requests merged in 2022-06, with the labels that each got.

#598 Update zh-tw.toml
  i18n/zh-tw.toml
Labels: translation, automerge

#595 Dark theme via DarkReader
  layouts/partials/header.html
  layouts/partials/navigators/navbar-2.html
  layouts/partials/navigators/navbar.html
  layouts/partials/navigators/theme-selector.html
  layouts/partials/scripts.html
  static/css/colortheme/colortheme.css
  static/icons/computer-svgrepo-com.svg
  static/icons/moon-svgrepo-com.svg
  static/icons/sun-svgrepo-com.svg
  static/js/darkmode-darkreader.js
  static/js/darkreader.js
  static/js/navbar.js
Labels: feature, automerge

#605 Use `RelPermalink` for background url
  layouts/_default/single.html
  layouts/partials/sections/achievements/entry.html
  layouts/partials/sections/home.html
Labels: bug, automerge

#606 Fix CSS for gist
  static/css/layouts/main.css
Labels: bug, automerge
