Repository hugo-toha/toha, pull requests merged in 2023-07, with the labels that each got.

#769 Fix Issue: Skills logo misaligned #753
  assets/styles/sections/skills.scss
Labels: bug, automerge

#770 Add extracurricular activities url
  layouts/partials/sections/education-alt.html
  layouts/partials/sections/education.html
Labels: feature, automerge

#772 Fix issue: #771Taken Courses (Show More and Show Less) buttons showed together
  assets/scripts/sections/education.js
  assets/styles/sections/education.scss
Labels: bug, automerge

#773 Add space between expanding icon and category name (Sidebar)
  layouts/partials/navigators/sidebar.html
Labels: automerge, bug-fix

#780 Fix CSS not being applied in tags
  assets/styles/layouts/list.scss
Labels: bug, bug-fix

#783 Fix index fetching during search
  assets/scripts/pages/search.js
Labels: bug, bug-fix

#782 Add possibility to show tags on post cards
  assets/styles/layouts/list.scss
  assets/styles/sections/recent-posts.scss
  exampleSite/config.yaml
  layouts/partials/cards/post.html
  layouts/partials/cards/recent-post.html
Labels: feature, automerge

#763 Support Cloudflare Web Analytics
  exampleSite/config.yaml
  layouts/partials/analytics.html
Labels: feature, automerge
