Repository hugo-toha/toha, pull requests merged in 2023-01, with the labels that each got.

#722 Update `config.yaml` for `exampleSite` to match new structure
  exampleSite/config.yaml
Labels: enhancement, automerge

#724 Fix build
  .github/workflows/build.yml
Labels: bug, automerge

#727 Brazilian Portuguese translation
  README.md
  i18n/pt-br.toml
Labels: translation, automerge
