Repository hugo-toha/toha, pull requests merged in 2023-11, with the labels that each got.

#833 Add minute translation for catalan, spanish and french
  i18n/ad.toml
  i18n/es.toml
  i18n/fr.toml
Labels: translation, automerge

#835 Refactor workflows (1)
  .eslintignore
  .github/workflows/build.yml
  .github/workflows/enforce-label.yml
  .github/workflows/md-link-checker.yml
  .github/workflows/merge-to-main.yml
  .github/workflows/project-automation-issue.yaml
  .github/workflows/project-automation-pr.yaml
  .github/workflows/pull-request.yml
  assets/scripts/sections/education.js
  exampleSite/config.yaml
  exampleSite/go.mod
  exampleSite/go.sum
  exampleSite/package-lock.json
  exampleSite/package.json
Labels: enhancement

#836 Add Netlify configuration
  netlify.toml
Labels: enhancement, automerge

#837 Add lighthouse score check
  .github/workflows/pull-request.yml
Labels: enhancement
