Repository hugo-toha/toha, pull requests merged in 2023-10, with the labels that each got.

#803 Remove re-write warning message
  README.md
Labels: enhancement, automerge

#799 Fixed navbar scroll spy (#798)
  assets/styles/layouts/main.scss
  layouts/partials/helpers/get-section-url.html
  layouts/partials/navigators/navbar.html
Labels: bug-fix

#790 fix dark mode: absolute to relative icon path
  layouts/partials/navigators/theme-selector.html
Labels: bug-fix

#786 Add section to feature some posts in the main page
  layouts/partials/sections/featured-posts.html
Labels: feature

#788 Create mastodon embed shortcode
  layouts/shortcodes/mastodon.html
Labels: feature

#804 Fix post author image position + responsiveness
  assets/styles/layouts/single.scss
  assets/styles/navigators/navbar.scss
  assets/styles/navigators/sidebar.scss
Labels: automerge, bug-fix

#807 Fix featured post section after update
  layouts/partials/sections/featured-posts.html
Labels: automerge, bug-fix

#812 Add input color
  assets/styles/components/texts.scss
Labels: automerge, bug-fix

#815 Justify post content (issue #831: Text in post is not justified)
  assets/styles/components/texts.scss
  assets/styles/layouts/single.scss
Labels: enhancement, automerge

#820 Fix search result card layout
  content/posts/_index.md
  content/search/search.bn.md
  content/search/search.cn.md
  content/search/search.de.md
  content/search/search.es.md
  content/search/search.fr.md
  content/search/search.hi.md
  content/search/search.id.md
  content/search/search.it.md
  content/search/search.jp.md
  content/search/search.ko.md
  content/search/search.md
  content/search/search.ru.md
  content/search/search.vn.md
Labels: automerge, bug-fix

#821 Fixed localization of post cards
  i18n/bn.toml
  i18n/en.toml
  i18n/it.toml
  layouts/_default/single.html
  layouts/partials/cards/post.html
Labels: translation, automerge

#826 Add self-hosted goat counter
  layouts/partials/analytics.html
Labels: feature, automerge, hacktoberfest

#828 Update Hugo version in README
  README.md
Labels: enhancement, automerge

#829 Add tooltiop for scroll-to-top button
  layouts/_default/single.html
Labels: enhancement, automerge

#830 Updated min hugo version required on theme configuration
  theme.toml
Labels: automerge, bug-fix
