Repository hugo-toha/toha, pull requests merged in 2024-04, with the labels that each got.

#914 add hebrew translation
  README.md
  i18n/he.toml
Labels: translation

#921 Add custom name in Navbar
  layouts/partials/navigators/navbar.html
Labels: feature

#918 Migrate to Bootstrap 5
  assets/styles/components/buttons.scss
  assets/styles/components/cards.scss
  assets/styles/components/links.scss
  assets/styles/layouts/single.scss
  assets/styles/navigators/navbar.scss
  assets/styles/sections/experiences.scss
  exampleSite/package-lock.json
  exampleSite/package.json
  layouts/_default/baseof.html
  layouts/_default/search.html
  layouts/_default/single.html
  layouts/index.html
  layouts/partials/cards/accomplishments.html
  layouts/partials/cards/post.html
  layouts/partials/cards/publication.html
  layouts/partials/footer.html
  layouts/partials/navigators/lang-selector.html
  layouts/partials/navigators/navbar.html
  layouts/partials/navigators/theme-selector.html
  layouts/partials/sections/about.html
  layouts/partials/sections/achievements/entry.html
  layouts/partials/sections/education-alt.html
  layouts/partials/sections/education.html
  layouts/partials/sections/experiences/vertical-line.html
  layouts/partials/sections/projects.html
  layouts/partials/sections/publications.html
  layouts/partials/sections/recent-posts.html
  package-lock.json
  package.hugo.json
  package.json
Labels: enhancement
