Repository hugo-toha/toha, pull requests merged in 2024-09, with the labels that each got.

#960 Added default theme
  assets/scripts/features/index.js
  assets/scripts/features/theme/index.js
  exampleSite/hugo.yaml
  layouts/_default/baseof.html
  layouts/index.html
  layouts/partials/helpers/get-esbuild-options.html
  layouts/partials/navigators/navbar.html
  layouts/partials/navigators/theme-selector.html
Labels: feature

#971 Fix auto-prefixer workflow
  assets/styles/components/cards.scss
  assets/styles/components/links.scss
  assets/styles/components/tables.scss
  assets/styles/layouts/list.scss
  assets/styles/layouts/main.scss
  assets/styles/sections/footer.scss
  assets/styles/sections/pdf-viewer.scss
  package-lock.json
  package.json
Labels: bug-fix

#982 Separate label enforcer job to separate workflow
  .github/workflows/enforce-lablel.yml
  .github/workflows/pull-request.yml
Labels: automerge

#975 Added Azerbaijan language
  README.md
  i18n/az.toml
Labels: translation

#972 Change npm package 'flag-icon-css' to 'flag-icons'
  data/toha/styles.yml
  exampleSite/hugo.yaml
  exampleSite/package-lock.json
  exampleSite/package.json
  hugo.yaml
  layouts/partials/navigators/lang-selector.html
  package-lock.json
  package.hugo.json
  package.json
Labels: bug-fix

#974 Align card texts and tag list to left
  assets/styles/components/cards.scss
  assets/styles/components/texts.scss
Labels: enhancement, automerge

#976 Fix perfect matching provisionally
  assets/scripts/pages/search.js
Labels: automerge, bug-fix

#979 Add category filter for skills
  assets/scripts/sections/index.js
  assets/scripts/sections/skills.js
  layouts/partials/cards/skill.html
  layouts/partials/sections/skills.html
Labels: feature

#963 Add copy code button
  assets/scripts/features/copyCode/copyCode.js
  assets/scripts/features/copyCode/index.js
  assets/scripts/features/index.js
  assets/styles/components/buttons.scss
  exampleSite/hugo.yaml
  exampleSite/package-lock.json
  exampleSite/package.json
  package.json
Labels: feature
