Repository hugo-toha/toha, pull requests merged in 2024-10, with the labels that each got.

#988 Add minute section in zh-cn and zh-tw UI translation
  i18n/zh-cn.toml
  i18n/zh-tw.toml
Labels: translation

#987 Add project image
  assets/styles/components/cards.scss
  layouts/partials/cards/project.html
Labels: enhancement, hacktoberfest-accepted

#1001 Add support for canonical links
  layouts/_default/baseof.html
  layouts/_default/single.html
Labels: feature

#1003 Add statcounter to statistics
  exampleSite/hugo.yaml
  layouts/_default/baseof.html
  layouts/partials/analytics.html
Labels: feature, hacktoberfest

#1005 Fix input focus and placeholder color for footer section
  assets/styles/sections/footer.scss
Labels: hacktoberfest, bug-fix
