Repository hugo-toha/toha, pull requests merged in 2024-05, with the labels that each got.

#936 Fix language selector when default language is not English
  exampleSite/hugo.yaml
  layouts/partials/navigators/lang-selector.html
Labels: bug-fix

#937 Fix passing google analytics id
  layouts/partials/analytics.html
Labels: automerge, bug-fix

#938 Added umami analitycs support
  README.md
  exampleSite/hugo.yaml
  layouts/partials/analytics.html
Labels: feature

#943 Fix font color of education pages in dark mode
  assets/styles/components/texts.scss
  assets/styles/sections/education.scss
Labels: bug-fix
