Repository hugo-toha/toha, pull requests merged in 2024-01, with the labels that each got.

#858 Refactor alert shortcode
  assets/styles/components/misc.scss
  assets/styles/mixins.scss
  assets/styles/variables.scss
  layouts/shortcodes/alert.html
Labels: bug, automerge

#861 Add `hugoVersion` info in config.yaml
  config.yaml
Labels: automerge

#863 Update README.md
  README.md
Labels: documentation, automerge

#864 Add Researchgate as contact option
  layouts/partials/footer.html
Labels: feature, automerge

#866 Add select maximum number of posts per page
  layouts/_default/list.html
  layouts/categories/list.html
  layouts/tags/list.html
Labels: feature, automerge

#869 Update local development guide
  README.md
  exampleSite/go.sum
Labels: documentation, automerge
