Repository hugo-toha/toha, pull requests merged in 2024-02, with the labels that each got.

#870 Add param profile to hide author in post
  layouts/_default/single.html
Labels: enhancement, automerge

#881 Fix active menu on sidebar not getting highlighted in dark mode
  assets/styles/components/links.scss
  exampleSite/config.yaml
Labels: bug, automerge

#882 Add company and school logos
  assets/styles/components/images.scss
  assets/styles/sections/experiences.scss
  layouts/partials/sections/education-alt.html
  layouts/partials/sections/education.html
  layouts/partials/sections/experiences.html
  layouts/partials/sections/experiences/experience-info.html
  layouts/partials/sections/experiences/multiple-positions.html
  layouts/partials/sections/experiences/positions.html
  layouts/partials/sections/experiences/single-position.html
Labels: feature, automerge

#883 Add dutch in Readme
  README.md
Labels: translation, automerge
