Repository hugo-toha/toha, pull requests merged in 2025-02, with the labels that each got.

#1031 Make Phone Number Clickable in Footer
  layouts/partials/footer.html
Labels: feature

#1032 fix: Create text-justify css class
  assets/styles/components/texts.scss
Labels: enhancement

#1033 Update minimum Hugo version to 0.142.0
  hugo.yaml
Labels: enhancement, dependencies

#1034 Make RSS feed path configurable
  exampleSite/hugo.yaml
  exampleSite/package-lock.json
  exampleSite/package.json
Labels: feature
